variable "env" {}
variable "subnet_ids" {}
variable "vpc_id" {}
variable "allow_cidr" {}
variable "component" {}
variable "app_port" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}
variable "instance_type" {}
variable "bastion_cidr" {}
variable "alb" {}
variable "listener" {}
variable "listener_priority" {}
variable "alb_arn" {}
variable "monitor_cidr" {}